version: '3.3'
services:
  frontend:
    container_name: frontend
    build: ./frontend
    restart: unless-stopped
    ports:
      - '8081:80'
  backend:
    container_name: backend
    build: ./backend
    networks:
      - backend-database
    restart: 'unless-stopped'
    ports:
      - '4000:3001'
    env_file:
      - ./.env
    depends_on:
      - db
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  db:
    container_name: postgres
    image: 'postgres'
    env_file:
      - ./.env
    networks:
      - backend-database
    restart: unless-stopped
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_PASSWORD=student
volumes:
  pg_data:
    driver: local

networks:
  backend-database: {}
